# Generated by Django 5.0.6 on 2024-05-21 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='admin_photos/')),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Puerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado_actual', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('puerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='admin_page.puerta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='admin_page.user')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('puerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.puerta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='admin_page.user')),
            ],
        ),
    ]
