# Generated by Django 5.0.6 on 2024-05-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='puerta_photos/'),
        ),
    ]
