# Generated by Django 5.0.6 on 2024-06-16 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_puerta_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actividad', models.DateField()),
                ('hora_actividad', models.TimeField()),
                ('puerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.puerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.user')),
            ],
        ),
    ]
